eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
 
 

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info
        

jwt:
 access:
  secret: MysuperSecretKeyForJWT1234567890098765432
  expiration: 900   # 15 min
 refresh:
  secret: MysuperSecrehfeyForJWT1234567890098765432
  expiration: 604800  # 7 days
 roles:
 admin: ROLE_ADMIN
 user: ROLE_USER
