eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
 
 

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info
        

jwt:
 access:
  secret: MysuperSecretKeyForJWT1234567890098765432dffgdfsgfgsfgsdfgfsfgffgsfg456w5w465w4rggfg4453
  expiration: 900   # 15 min
 refresh:
  secret: MysuperSecretKeyForJWT123456789009876hd7532dffgdfsgfgsfgsdfgfsfgffgsfg456w5w465w4rggfg4453
  expiration: 604800  # 7 days
 roles:
 admin: ROLE_ADMIN
 user: ROLE_USER
 
spring:
  kafka:
   bootstrap-servers: localhost:9092
   consumer:
     group-id: order-service
     key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
     value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
     properties:
       spring.json.trusted.packages: com.microtest.event
   producer:
     key-serializer: org.apache.kafka.common.serialization.StringSerializer
     value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cloud:
   config:
    override-none: true


app:
  kafka:
    topic:
      order: orders-topic3
      partition: 3
      replicate: 1
    dlt:
      order: orders-topic3.DLT
      partition: 3
      replicate: 1  
    
    
    
